[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3"
numpy = "^1.21"
scikit-learn = "^0.24"
streamlit = "^0.84"
great-expectations = "^0.13"
featuretools = "^0.23"
shap = "^0.39"
pydantic = "^1.8"
openai>=0.27.0
